### ISSUE TITLE
is there a way to locate apiproxy folder generated by a127?

### ISSUE THREAD

**Issue by dzuluaga** [apigee-127/a127#12]
I've been testing a127 and it's been great!!!

Something that might be useful though is to include the location of the apiproxy folder. This provides a way to integrate a127 with other tools such as: Apigee Deploy Maven or even Grunt Plugins to extend the configurability of the bundle, so that it can run tasks to apply coding standards with JSHint, ESLint, search and replace XML tokens with XMLPoke, run unit tests with JMeter or Mocha, etc.

**Comment by theganyo** [comment]
Thanks. I looked into this a bit and while we have no apiproxy folder for our deployments, from what I understand from @jwest-apigee, this could be done by putting your project into the apiproxy/resources/node folder and deploying that manually.

**Comment by theganyo** [comment]
I'm closing this for now. If we need to revisit, please let me know.
