### ISSUE TITLE
app.js bodyParser comment should bypass the connect 3.0 deprecation notice.

### ISSUE THREAD

**Issue by r3mus** [apigee-127/a127#20]
Since Express 3 uses an old embedded version of connect, we should probably change the comment to include the deprecated `bodyParser` with:

```
app.use(express.json());
app.use(express.urlencoded());
```

Source: http://stackoverflow.com/questions/19581146/how-to-get-rid-of-connect-3-0-deprecation-alert

**Comment by theganyo** [comment]
This has been done!
