### ISSUE TITLE
Invalid/corrupt Usergrid launcher jar file

### ISSUE THREAD

**Issue by cwarny** [apigee-127/a127#21]
I am on Mac OS X Yosemite 10.10.1. I downloaded apigee-127 `npm install -g apigee-127`, then downloaded usergrid `a127 usergrid download`. When I then try to start usergrid, I get the following error message:

```
$ sudo a127 usergrid start
starting...
.timeout
failed to start. Log tail:
Error: Invalid or corrupt jarfile /Users/cwarny/.a127/usergrid/usergrid-launcher-0.0.29.jar
```

**Comment by theganyo** [comment]
Moved issue to usergrid downloader module.
