### ISSUE TITLE
question: can the a127 config system be used for custom config data that is not directly tied to a volos plugin?

### ISSUE THREAD

**Issue by emcpadden** [apigee-127/a127#33]
I really like the a127 configuration and how you can add configuration to the swagger files that have values that can be replaced with values in the config/default.yaml and overridden by the config/[account].yam and then again by settings in the apigee account.  

I had a question about something that I would like to do and am not sure if there is a way to already handle this (or if there is a better way I should be doing this or thinking about this):

I was wondering if there is a way to add arbitrary config data into the swagger file that I could override in the same way.  The config data I would like to add is not directly tied to any of the volos plugins but instead things that would allow me to point at different endpoints or use different configurations inside my api facade that would change depending on whether I was running locally or running in apigee.

I just seems like it would be nice if I could do this in a way that piggybacks on the a127/swagger configuration system.

Thanks!
...Ed

**Comment by theganyo** [comment]
Hey Ed. You bet! You can use any of the config values you set in the yaml files (or in the the account using the setValue command) in your Swagger. It basically works like this:

    x-a127-config:
        myNameFromConfig: &myVariableName "A Default Value"

... later....

    someConfiguredValue: *myVariableName

Is that the magic you're looking for?

Scott

**Comment by theganyo** [comment]
Oh! And the values don't just have to be strings. You can also replace whole structures:

default.yaml:

    myNameFromConfig
      myValue1: New Value
      myValue2: Another Value

Swagger:

    x-a127-config:
      myNameFromConfig: &myVariableName
        myValue1: Replaced
        myValue2: Replaced as well

...later (as before)...

    someConfiguredValue: *myVariableName

**Comment by emcpadden** [comment]
Thanks!  ... one more follow on question:

How do I access that custom config key from within my node project?  Is there something I need to call on the config object returned in the callback on the a127.init method inside app.js?

**Comment by theganyo** [comment]
You bet. You can access it directly:

    a127.init(function(config) {
      app.use(a127.middleware(config));

      var myConfig = config['myNameFromConfig'];

**Comment by emcpadden** [comment]
Perfect!

**Comment by WWitman** [comment]
Hi Ed, I updated the a127 configuration doc to make this more clear. Would this have been helpful information?

https://github.com/apigee-127/a127-documentation/wiki/Configuration#arbitrary

**Comment by emcpadden** [comment]
Yes that does help.  Actually, in my case I want to just have some arbitrary config data that isn't used directly by the swagger file.  For instance, it might be data that we will use inside our node code.  For example, it might be some configuration data that we need to be able to get at some other 3rd party service from within our node api facade.

Now, in the node app, I can get at that config info the way Scott described above:
var myConfig = config['myNameFromConfig'];

If I want to get at this same data from inside my controller method, I see that I can find it this way:

function hello(req, res) {
  // variables defined in the Swagger document can be referenced using req.swagger.params.{parameter_name}
  var name = req.swagger.params.name.value || 'stranger';
  var hello = util.format('Hello, %s!', name);

   **var myConfig = req.swagger.swaggerObject['x-a127-config'].myNameFromConfig;**

  // this sends back a JSON response which is a single string
  res.json(hello);
}

*Is this a good way to do this by going thru the req.swagger.swaggerObject?*

*Or is there some other way to get at config data from within the controller methd?*

Thanks for all your help understanding this.

**Comment by theganyo** [comment]
The horror!  ;)

No, if you just want to access your config in a controller, you don't need to put it in the Swagger at all. (In fact, perhaps we should add the capability to grab config from controllers. Maybe add a req.a127.config() method similar to the req.a127.resource() method. Let me know what you think.)

In the mean time, if you like that idea, you can just add config to all incoming requests so you can access it in your controllers. In your app.js in the config, you can just add a middleware like this:

    a127.init(function(config) {

      // add config to the request
      app.use(function(req, res, next) {
        req.config = config;
        next();
      });

      app.use(a127.middleware(config));


Then, in your controller, just access it like this:

    var myConfig = req.config.nyNameFromConfig;

**Comment by emcpadden** [comment]
Cool!  Adding the middleware as you suggest works for me.

Having the configuration on the request like you mention also works (req.a127.config) but not necessary if you'd rather not.

Thanks again!

**Comment by theganyo** [comment]
You bet!

**Comment by apobbati** [comment]
Is there a way to set configuration values programmatically? I would like these values to be injected from an environment variable.

**Comment by apobbati** [comment]
Is it possible to change the location of the configuration directory?

**Comment by theganyo** [comment]
You bet. You can set values on the config object directly here:

```
a127.init(function(config) {

  /// set your config values here ///
  config.whatever = 'foo';

  app.use(a127.middleware(config));
```

But currently, no, the config directory itself is not configurable.
