### ISSUE TITLE
Cannot start project in mock mode

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/a127#36]
Following the instructions at https://github.com/apigee-127/a127-documentation/wiki/Mock-mode#starting
I am still not able to start a project in mock mode. It seems it cannot find the route to the /weather path.

I get:

```
Cannot GET /weather/
```

Is there any setting I am missing in any of the yaml configuration options?. Please advice. This feature seem to be pretty useful. I still have yet to see it in action..

Following is a debug output:

```
  connect:dispatcher query  : /weather +9s
  connect:dispatcher expressInit  : /weather +0ms
  connect:dispatcher anonymous  : /weather +1ms
  swagger-tools:middleware:metadata GET /weather +9s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +1ms
  swagger-tools:middleware:security GET /weather +0ms
  swagger-tools:middleware:security   Will process: yes +0ms
  swagger handle req: /weather +9s
  swagger creating auth chain for: undefined +0ms
  swagger-tools:middleware:validator GET /weather +1ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger creating volos chain for: undefined +1ms
  swagger-tools:middleware:router GET /weather +1ms
  swagger-tools:middleware:router   Will process: yes +0ms
  swagger-tools:middleware:router   Route handler: false +0ms
  swagger-tools:middleware:router   Mock mode: false +0ms
  finalhandler default 404 +4ms
  connect:dispatcher query  : /weather/ +16s
  connect:dispatcher expressInit  : /weather/ +0ms
  connect:dispatcher anonymous  : /weather/ +0ms
  swagger-tools:middleware:metadata GET /weather/ +16s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +1ms
  swagger-tools:middleware:metadata   Processing Parameters +0ms
  swagger-tools:middleware:security GET /weather/ +0ms
  swagger-tools:middleware:security   Will process: yes +0ms
  swagger handle req: /weather/ +16s
  swagger-tools:middleware:validator GET /weather/ +0ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:router GET /weather/ +0ms
  swagger-tools:middleware:router   Will process: yes +0ms
  swagger-tools:middleware:router   Route handler: false +0ms
  swagger-tools:middleware:router   Mock mode: false +1ms
  finalhandler default 404 +2ms
```

**Comment by theganyo** [comment]
No, there nothing special to configure: just the command line option. But it looks like you didn't start in mock mode correctly. See this line in your log file:

    swagger-tools:middleware:router   Mock mode: false +1ms

Please be sure you are starting the app using:

    a127 project start --mock

or

    a127 project start -m

**Comment by jcferrer** [comment]
I did start the project with the --m option and yes, I noticed the Mock mode: false in the debug, that's what I was trying to point out.

Using a127 v0.11.3:

```
a127 project create example
cd example
DEBUG=* a127 project start --m
```
you then do the typical hello request and get the typical "Hello, stranger" (actually generated by the sample controller).
 
The example debug output shows
```
swagger-tools:middleware:router   Mock mode: false
```

**Comment by theganyo** [comment]
Hey JC,
I've been unable to replicate your first issue. I've tried uninstalling and reinstalling apigee-127 and creating a new app like you did with no issue - mock mode comes up fine. Be sure everything you have is up to date. Also, when you start the app in mock mode, please check your project's  config/.a127_secrets file. It should have configuration item like you added to default.yaml:
```
_a127_start_config:
  debug: null
  mock: true
```
Your second issue, however, I can recreate. I'm looking into why it's hanging on the second request.
Scott

**Comment by jcferrer** [comment]
Scott,

While you dig into the second issue, I wanted to tell you that I have found why I was not able to run the app in mock mode.

The problem was that the .a127_secrets file was not being created when the project was executed. The reason being the file ```~/.a127/accounts``` had no accounts registered. It seems that you have to have a deployer account created first in order to have a127 create and populate the ./config/.a127_secrets.

I got it to work by creating a local deployer account.

Looking forward to hear from you on that request hanging issue.

Thanks

JC

**Comment by theganyo** [comment]
Thanks! That's super useful information.
