### ISSUE TITLE
Change dynamic swagger-editor port to static (consistent) port

### ISSUE THREAD

**Issue by brandonscript** [apigee-127/a127#37]
Changing the port on the swagger-editor to be a standard (consistent) port number would allow preferences to persist throughout the editing process, and would also allow bookmarking.

Recommend making this property configurable or override-able somehow (maybe in the swagger.yaml itself?) in the project so that if you have multiple projects running you can easily adjust the port number to work around conflicts.

**Comment by theganyo** [comment]
The port can now be specified via PORT env var. See: https://github.com/apigee-127/a127/pull/53
