### ISSUE TITLE
Injecting own middleware into the a127 middleware chain

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/a127#38]
I have a middleware that I would like to include for execution after all swagger security, validation, etc. but right before the swagger router calls the corresponding controller.

The only way I get to execute my middleware is by adding it before the a127 chain has been inserted
```
app.use(myHandler());
app.use(a127.middleware(config));
```
but is too early for my purposes. Adding it after the a127.middleware, the handler does not execute.

Going through the code, I found that the ```a127-magic/lib/middleware.js``` returns a prebuilt chain
```
 return chain([
    swaggerTools.swaggerMetadata(magic.swaggerObject),
    swaggerTools.swaggerSecurity(magic.volosAuth.swaggerSecurityHandlers),
    magic.volosAuth,
    swaggerTools.swaggerValidator(validatorConfig),
    magic.volosApp,
    addFuncsToRequest(a127Funcs),
    swaggerTools.swaggerRouter(routerConfig)
  ]);
```
I was able to force my middleware into the chain, but the solutions is kind of ugly.

Is there anyway that I am not aware of, to actually have a127 allow for this functionality?

Please advise.

Thanks

JC

**Comment by theganyo** [comment]
Good news: I've actually already started working on a feature that can address this. In the meantime, maybe just call the middleware from your controllers?

**Comment by prabhatjha** [comment]
:thumbsup:

On Thu, Feb 19, 2015 at 9:40 AM, Scott Ganyo <notifications@github.com>
wrote:

> Good news: I've actually already started working on a feature that can
> address this. In the meantime, maybe just call the middleware from your
> controllers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee-127/a127/issues/38#issuecomment-75098827>.
>



-- 
Cheers,
Prabhat
---------------------------
Help spread www.eejot.org

**Comment by jcferrer** [comment]
Great Scott,

Another possibility is to actually create the middleware as a volos provider. It's a little more involved but I got it to work using the x-a127-apply property and defining my provider the same way the cache or quota are defined.

I am waiting for your solution, it would be probably less involved.

Thanks

**Comment by theganyo** [comment]
Yup. You could do that too! I figured that would be too much work... but congrats on getting it done! :)

Yes, the new solution will definitely be less involved. :)

**Comment by theganyo** [comment]
This will be available in swagger-node. See: https://github.com/swagger-api/swagger-node/issues/294

**Comment by jcferrer** [comment]
Thanks Scott!

JC Ferrer
