### ISSUE TITLE
Split swagger definition into multiple yaml files

### ISSUE THREAD

**Issue by agonbina** [apigee-127/a127#41]
Is this possible? Seems like you would need to have some sort of file hierarchy(folders/files) to quickly move around and make changes in an extensive API definition, instead of scrolling up and down like a maniac lol. I tried the suggestion in this issue https://github.com/swagger-api/swagger-editor/issues/233 but the live editor never picks up the new files, you have to go to preview mode to see the external files get included and even then the definition is not loaded up correctly.

Anyone was able to accomplish this?

**Comment by mohsen1** [comment]
if you're using `$ref`, it's value should be **valid** relative or absolute URL.

**Comment by agonbina** [comment]
Indeed, I have this:
```js
paths:
  /subscriptions:
    $ref: subscriptions.yaml
```

The subscriptions.yaml file is placed in the same directory as swagger.yaml(as generated by the a127 cli create command).

And this is what's in the subscriptions.yaml file:
```js
get:
  x-swagger-router-controller: subscriptions
  x-a127-apply: {}
  description: Returns all subscriptions for this user
  responses:
    200:
      description: Success
```

When I first add the line that references the external file, the editor shows an error pointing to this line and says its not a valid object. After you go on preview mode the error goes away, I can see the /subscriptions path too, but it seems like its treating this path as a new "Swagger Object" instead of parsing the actual content thats in it.

**Comment by mohsen1** [comment]
Do you see a request made to `subscriptions.yaml`? 

@whitlockjc Does SwaggerTools resolver work with relative paths too?

**Comment by jasonh-n-austin** [comment]
FYI this is en route for swagger-js:
https://github.com/swagger-api/swagger-js/issues/417

Already updated in the Swagger spec:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#referenceObject
...and examples
https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/yaml/petstore-separate

**Comment by telasai1** [comment]
hi, @jasonh-n-austin 

I referred to your example and tried this:

"$ref": "parameters.json#/tagsParam" 
or  
"$ref": "parameters.yaml#/tagsParam" 

However $ref works only if i refer definition from the same json/yaml file. Cross reference to other YAML file is not working.

How did you get this to work?

This is what is there in my local swagger.json file:

 "parameters": [
                    {
                        "name": "loanAgreement",
                        "in": "body",
                        "description": "loan Agreement details",
                        "required": true,
                        "schema": {
                            "$ref": "parameters.json#/tagsParam"
                        }
                    }

This is what i see in the swagger-ui:

![swagger](https://cloud.githubusercontent.com/assets/9929809/8253637/62c35b36-16af-11e5-87d6-39cb0a3e0eaf.jpg)

Thanks

**Comment by jasonh-n-austin** [comment]
@telasai1 I know @fehguy said it was fixed in `swagger-js`, but I think there's a downstream series of tools and apps (notably apigee stuff, which is why I brought it up over here) that may need updating to work properly. I hadn't tried it yet in swagger-ui, I'll check it out and see if I can track down if there are existing issues etc.

**Comment by telasai1** [comment]
hi, 
any updates on this.. 

Thanks
Iranna

**Comment by arnaud-deprez** [comment]
I also have the issue. 
The swagger editor is definitely not able to resolve external file.

Any updates ?

**Comment by SameerSiddiqui** [comment]
Hello, is there a fix out there for referring external .YAML files in my swagger.yaml file ? I want to split my swagger file into Paths.Yaml, and so forth. I keep on getting swagger validation error if i pass an outside yaml file in $ref.

**Comment by GingerCatNL** [comment]
Any update on this ?

**Comment by ianseyer** [comment]
+1

**Comment by JanBlessenohl** [comment]
+1

**Comment by Narcotic** [comment]
+1

**Comment by agonbina** [comment]
I'm closing this as I no longer use the product.
