### ISSUE TITLE
Need more documentation toward SSL request with Apigee 127 

### ISSUE THREAD

**Issue by Mattzr** [apigee-127/a127#46]
Hi,

I think documentation is missing regarding SSL request from node.js app hosted in Apigee Edge. The way of doing was to setup target server with truststore/ keystore and simply specify the virtualhosts to use in the "HTTPProxyConnection" but can't see its equivalent for apigee 127 app / node.js app

I appreciate that a127 "account create acc" prompt us with virtualhost details but it's like they are used only for routing and not for callout requests.

**Comment by theganyo** [comment]
Sorry, I'm not sure what you're asking. 

On Apigee Edge, a Node.js app is simply deployed as a Proxy and is subject to the same constraints any other Edge Proxy is. There is nothing special that a127 does with regards to this. The "a127 account create" is largely just gathering information that it uses for deployment of your proxy (and allows for account-based custom configuration, if you choose to use that feature).

**Comment by Mattzr** [comment]
Well - I believe "target servers" setup is not reusable on apigee 127. How should we handle TLS/SSL requests for 2 ways SSL in that case ? as all the certs are basically setup in Apigee Edge for the virtual hosts.

**Comment by theganyo** [comment]
Ah. Good question. That I do not know. Have you tried Apigee support - or the Apigee Community boards (https://community.apigee.com)? 

Also, I'll /cc somebody else that might have an idea on this. @prabhatjha

**Comment by Mattzr** [comment]
I tried the community portal but I haven't found answers. However - I've seen in the Apigee documentation that it is handled slightly differently using node tls module and to contact support desk to have more details.

**Comment by Mattzr** [comment]
I got to make my app working but I had to setup the whole stuff again...(all process of reissuing certs etc....). I believe target server's trustore/keystores are not reusable...

**Comment by theganyo** [comment]
Good to know, thanks!
